### ISSUE TITLE
JSON.generate throw error for marshal.dump object data

### ISSUE THREAD

**Issue by gotar** [ruby/json#204]
json (1.8.1)
ruby 2.1.0p0 (2013-12-25 revision 44422) [x86_64-darwin12.0]

``` ruby
2.1.0 :002 > JSON.generate(Marshal.dump(Time.now))
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
    from /Users/gotar/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:223:in `encode'
    from /Users/gotar/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:223:in `generate'
    from /Users/gotar/.rvm/rubies/ruby-2.1.0/lib/ruby/2.1.0/json/common.rb:223:in `generate'
    from (irb):2
    from /Users/gotar/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'

# The same

Marshal.dump(Time.now).to_json
Encoding::UndefinedConversionError: "\x88" from ASCII-8BIT to UTF-8
    from (irb):3:in `encode'
    from (irb):3:in `to_json'
    from (irb):3
    from /Users/gotar/.rvm/rubies/ruby-2.1.0/bin/irb:11:in `<main>'

```

But have those problems in different ruby versions too

**Comment by ChrisCPO** [comment]
@sharp @gotar Did you find an an answer to this. I'm having an issue with this on rails 5.1 and ruby 5.5
```
[16] pry(main)> Marshal.dump(User.first).to_json
Encoding::UndefinedConversionError: "\x80" from ASCII-8BIT to UTF-8
```

**Comment by byroot** [comment]
I don't think this is a bug. JSON strings can only contain valid UTF-8, `Marshal.dump` produce binary data. You may need to use `Base64` encoding or similar.
