### ISSUE TITLE
JSON gem should assume UTF-8 when $LANG not set

### ISSUE THREAD

**Issue by et304383** [ruby/json#248]
I am trying to run Berkshelf unattended through AWS CodeDeploy.  As a result, nearly no environment variables are set.

Here is the output I get:

```
/opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `encode': "\xE2" on US-ASCII (Encoding::InvalidByteSequenceError)
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `initialize'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `new'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/json-1.8.2/lib/json/common.rb:155:in `parse'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:473:in `from_json'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook/metadata.rb:29:in `from_json'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/ridley-4.1.2/lib/ridley/chef/cookbook.rb:36:in `from_path'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cached_cookbook.rb:15:in `from_store_path'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:108:in `block in cookbooks'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:98:in `collect'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cookbook_store.rb:98:in `cookbooks'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver/graph.rb:8:in `populate_store'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/resolver.rb:73:in `resolve'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:175:in `install_from_universe'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/installer.rb:39:in `run'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:374:in `install'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:583:in `block in vendor'
        from /opt/chefdk/embedded/lib/ruby/2.1.0/tmpdir.rb:88:in `mktmpdir'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/berksfile.rb:581:in `vendor'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:387:in `vendor'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:52:in `dispatch'
        from /opt/chefdk/embedded/lib/ruby/gems/2.1.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
        from /opt/chefdk/embedded/apps/berkshelf/lib/berkshelf/cli.rb:27:in `execute!'
        from /opt/chefdk/embedded/apps/berkshelf/bin/berks:5:in `<top (required)>'
        from /usr/bin/berks:43:in `load'
        from /usr/bin/berks:43:in `<main>'
```

This can only be fixed by `export LANG=en_US.UTF-8` but that shouldn't be necessary for any application to function.

Is it possible set a reasonable default?

Note this seems to be the primary issue, but I think the consensus is that this is an issue with the JSON gem:
https://github.com/berkshelf/berkshelf-api/issues/112

**Comment by miketheman** [comment]
@eric-tucker I looked into this a while back on the berkshelf-api issue, and mentioned that this gem appears to load everything in utf-8 already - see here: https://github.com/flori/json/blame/5a4331918f61a8a4dbe12df8a12f66e5b4e4811a/README.rdoc#L16-L17

I think it boils down to the execution environment not having the installed UTF-8 language - see notes here: https://github.com/berkshelf/berkshelf-api/issues/112#issuecomment-72291084

**Comment by eric-tucker** [comment]
I agree that missing the LANG environment variable is the CAUSE, but I'm suggesting that the application should be able to handle this variable missing.  Is this not something that can be fixed?

**Comment by miketheman** [comment]
I'll leave it up to @flori & any other maintainers to chime in - but I don't think it's this particular gem's responsibility to handle this case.

**Comment by byroot** [comment]
Doubt this is still a problem. In any case, the caller is responsible for providing properly encoded strings.
