### ISSUE TITLE
npe in 2.7.3 & 2.7.4 in ruby 3.4-preview2

### ISSUE THREAD

**Issue by hurricup** [ruby/json#653]
```

TypeError: wrong argument type nil (expected String)
/usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/ext/generator/state.rb:49:in 'JSON::Ext::Generator::State#indent='
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/ext/generator/state.rb:49:in 'block in JSON::Ext::Generator::State#configure'
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/ext/generator/state.rb:46:in 'Hash#each'
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/ext/generator/state.rb:46:in 'JSON::Ext::Generator::State#configure'
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/ext/generator/state.rb:27:in 'JSON::Ext::Generator::State#initialize'
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/common.rb:307:in 'Class#new'
    /usr/share/rvm/gems/ruby-3.4.0-preview2@debase30/gems/json-2.7.4/lib/json/common.rb:307:in 'JSON.generate'

```
Same in 2.7.2 works fine

**Comment by casperisfine** [comment]
Could you provide a reproduction? Because `JSON.generate({}, indent: nil)` did raise in `2.7.2` already, so I'm not sure what you were doing that used to work:

```ruby
>> JSON::VERSION
=> "2.7.2"
>> JSON.generate({}, indent: nil)
/Users/byroot/.gem/ruby/3.3.4/gems/json-2.7.2/lib/json/ext/generator/state.rb:49:in `indent=': wrong argument type nil (expected String) (TypeError)

              self.indent = value
                            ^^^^^
```

**Comment by casperisfine** [comment]
Alright, seems like the regression was between `2.7.1` and `2.7.2`

```ruby
>> gem 'json', '2.7.1'; require 'json'; JSON::VERSION
=> "2.7.1"
>> JSON.generate({}, indent: nil)
=> "{}"
```
